# Usamos la imagen oficial de MySQL versión 8.0
FROM mysql:8.0

# Configuramos las credenciales y la base de datos inicial
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=unidos_animales

# Exponemos el puerto por defecto de MySQL
EXPOSE 3306